namespace Neovolve.CodeAnalysis.ChangeTracking.UnitTests.ChangeTables
{
    using System;
    using FluentAssertions;
    using Neovolve.CodeAnalysis.ChangeTracking.ChangeTables;
    using Neovolve.CodeAnalysis.ChangeTracking.Models;
    using Xunit;

    public class PropertyModifiersChangeTableTests
    {
        [Theory]
        [ClassData(typeof(EnumCombinationsDataSet<PropertyModifiers>))]
        public void CalculateChangeHandlesAllPossibleValues(PropertyModifiers oldValue, PropertyModifiers newValue)
        {
            var sut = new PropertyModifiersChangeTable();

            Action action = () => sut.CalculateChange(oldValue, newValue);

            action.Should().NotThrow();
        }

        // @formatter:off — disable formatter after this line
        [Theory]
        [InlineData(PropertyModifiers.None, PropertyModifiers.None, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.None, PropertyModifiers.Abstract, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.None, PropertyModifiers.New, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.None, PropertyModifiers.Override, SemVerChangeType.Feature)]
        [InlineData(PropertyModifiers.None, PropertyModifiers.Sealed, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.None, PropertyModifiers.Static, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.None, PropertyModifiers.Virtual, SemVerChangeType.Feature)]
        [InlineData(PropertyModifiers.None, PropertyModifiers.AbstractOverride, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.None, PropertyModifiers.NewAbstract, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.None, PropertyModifiers.NewAbstractVirtual, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.None, PropertyModifiers.NewStatic, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.None, PropertyModifiers.NewVirtual, SemVerChangeType.Feature)]
        [InlineData(PropertyModifiers.None, PropertyModifiers.SealedOverride, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.Abstract, PropertyModifiers.None, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Abstract, PropertyModifiers.Abstract, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.Abstract, PropertyModifiers.New, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Abstract, PropertyModifiers.Override, SemVerChangeType.Feature)]
        [InlineData(PropertyModifiers.Abstract, PropertyModifiers.Sealed, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Abstract, PropertyModifiers.Static, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Abstract, PropertyModifiers.Virtual, SemVerChangeType.Feature)]
        [InlineData(PropertyModifiers.Abstract, PropertyModifiers.AbstractOverride, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.Abstract, PropertyModifiers.NewAbstract, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.Abstract, PropertyModifiers.NewAbstractVirtual, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.Abstract, PropertyModifiers.NewStatic, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Abstract, PropertyModifiers.NewVirtual, SemVerChangeType.Feature)]
        [InlineData(PropertyModifiers.Abstract, PropertyModifiers.SealedOverride, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.New, PropertyModifiers.None, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.New, PropertyModifiers.Abstract, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.New, PropertyModifiers.New, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.New, PropertyModifiers.Override, SemVerChangeType.Feature)]
        [InlineData(PropertyModifiers.New, PropertyModifiers.Sealed, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.New, PropertyModifiers.Static, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.New, PropertyModifiers.Virtual, SemVerChangeType.Feature)]
        [InlineData(PropertyModifiers.New, PropertyModifiers.AbstractOverride, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.New, PropertyModifiers.NewAbstract, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.New, PropertyModifiers.NewAbstractVirtual, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.New, PropertyModifiers.NewStatic, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.New, PropertyModifiers.NewVirtual, SemVerChangeType.Feature)]
        [InlineData(PropertyModifiers.New, PropertyModifiers.SealedOverride, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.Override, PropertyModifiers.None, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Override, PropertyModifiers.Abstract, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Override, PropertyModifiers.New, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Override, PropertyModifiers.Override, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.Override, PropertyModifiers.Sealed, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Override, PropertyModifiers.Static, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Override, PropertyModifiers.Virtual, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.Override, PropertyModifiers.AbstractOverride, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Override, PropertyModifiers.NewAbstract, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Override, PropertyModifiers.NewAbstractVirtual, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Override, PropertyModifiers.NewStatic, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Override, PropertyModifiers.NewVirtual, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.Override, PropertyModifiers.SealedOverride, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Sealed, PropertyModifiers.None, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.Sealed, PropertyModifiers.Abstract, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Sealed, PropertyModifiers.New, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.Sealed, PropertyModifiers.Override, SemVerChangeType.Feature)]
        [InlineData(PropertyModifiers.Sealed, PropertyModifiers.Sealed, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.Sealed, PropertyModifiers.Static, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Sealed, PropertyModifiers.Virtual, SemVerChangeType.Feature)]
        [InlineData(PropertyModifiers.Sealed, PropertyModifiers.AbstractOverride, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Sealed, PropertyModifiers.NewAbstract, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Sealed, PropertyModifiers.NewAbstractVirtual, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Sealed, PropertyModifiers.NewStatic, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Sealed, PropertyModifiers.NewVirtual, SemVerChangeType.Feature)]
        [InlineData(PropertyModifiers.Sealed, PropertyModifiers.SealedOverride, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.Static, PropertyModifiers.None, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Static, PropertyModifiers.Abstract, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Static, PropertyModifiers.New, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Static, PropertyModifiers.Override, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Static, PropertyModifiers.Sealed, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Static, PropertyModifiers.Static, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.Static, PropertyModifiers.Virtual, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Static, PropertyModifiers.AbstractOverride, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Static, PropertyModifiers.NewAbstract, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Static, PropertyModifiers.NewAbstractVirtual, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Static, PropertyModifiers.NewStatic, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.Static, PropertyModifiers.NewVirtual, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Static, PropertyModifiers.SealedOverride, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Virtual, PropertyModifiers.None, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Virtual, PropertyModifiers.Abstract, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Virtual, PropertyModifiers.New, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Virtual, PropertyModifiers.Override, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.Virtual, PropertyModifiers.Sealed, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Virtual, PropertyModifiers.Static, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Virtual, PropertyModifiers.Virtual, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.Virtual, PropertyModifiers.AbstractOverride, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Virtual, PropertyModifiers.NewAbstract, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Virtual, PropertyModifiers.NewAbstractVirtual, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Virtual, PropertyModifiers.NewStatic, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.Virtual, PropertyModifiers.NewVirtual, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.Virtual, PropertyModifiers.SealedOverride, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.AbstractOverride, PropertyModifiers.None, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.AbstractOverride, PropertyModifiers.Abstract, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.AbstractOverride, PropertyModifiers.New, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.AbstractOverride, PropertyModifiers.Override, SemVerChangeType.Feature)]
        [InlineData(PropertyModifiers.AbstractOverride, PropertyModifiers.Sealed, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.AbstractOverride, PropertyModifiers.Static, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.AbstractOverride, PropertyModifiers.Virtual, SemVerChangeType.Feature)]
        [InlineData(PropertyModifiers.AbstractOverride, PropertyModifiers.AbstractOverride, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.AbstractOverride, PropertyModifiers.NewAbstract, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.AbstractOverride, PropertyModifiers.NewAbstractVirtual, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.AbstractOverride, PropertyModifiers.NewStatic, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.AbstractOverride, PropertyModifiers.NewVirtual, SemVerChangeType.Feature)]
        [InlineData(PropertyModifiers.AbstractOverride, PropertyModifiers.SealedOverride, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.NewAbstract, PropertyModifiers.None, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.NewAbstract, PropertyModifiers.Abstract, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.NewAbstract, PropertyModifiers.New, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.NewAbstract, PropertyModifiers.Override, SemVerChangeType.Feature)]
        [InlineData(PropertyModifiers.NewAbstract, PropertyModifiers.Sealed, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.NewAbstract, PropertyModifiers.Static, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.NewAbstract, PropertyModifiers.Virtual, SemVerChangeType.Feature)]
        [InlineData(PropertyModifiers.NewAbstract, PropertyModifiers.AbstractOverride, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.NewAbstract, PropertyModifiers.NewAbstract, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.NewAbstract, PropertyModifiers.NewAbstractVirtual, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.NewAbstract, PropertyModifiers.NewStatic, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.NewAbstract, PropertyModifiers.NewVirtual, SemVerChangeType.Feature)]
        [InlineData(PropertyModifiers.NewAbstract, PropertyModifiers.SealedOverride, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.NewAbstractVirtual, PropertyModifiers.None, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.NewAbstractVirtual, PropertyModifiers.Abstract, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.NewAbstractVirtual, PropertyModifiers.New, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.NewAbstractVirtual, PropertyModifiers.Override, SemVerChangeType.Feature)]
        [InlineData(PropertyModifiers.NewAbstractVirtual, PropertyModifiers.Sealed, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.NewAbstractVirtual, PropertyModifiers.Static, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.NewAbstractVirtual, PropertyModifiers.Virtual, SemVerChangeType.Feature)]
        [InlineData(PropertyModifiers.NewAbstractVirtual, PropertyModifiers.AbstractOverride, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.NewAbstractVirtual, PropertyModifiers.NewAbstract, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.NewAbstractVirtual, PropertyModifiers.NewAbstractVirtual, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.NewAbstractVirtual, PropertyModifiers.NewStatic, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.NewAbstractVirtual, PropertyModifiers.NewVirtual, SemVerChangeType.Feature)]
        [InlineData(PropertyModifiers.NewAbstractVirtual, PropertyModifiers.SealedOverride, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.NewStatic, PropertyModifiers.None, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.NewStatic, PropertyModifiers.Abstract, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.NewStatic, PropertyModifiers.New, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.NewStatic, PropertyModifiers.Override, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.NewStatic, PropertyModifiers.Sealed, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.NewStatic, PropertyModifiers.Static, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.NewStatic, PropertyModifiers.Virtual, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.NewStatic, PropertyModifiers.AbstractOverride, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.NewStatic, PropertyModifiers.NewAbstract, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.NewStatic, PropertyModifiers.NewAbstractVirtual, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.NewStatic, PropertyModifiers.NewStatic, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.NewStatic, PropertyModifiers.NewVirtual, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.NewStatic, PropertyModifiers.SealedOverride, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.NewVirtual, PropertyModifiers.None, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.NewVirtual, PropertyModifiers.Abstract, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.NewVirtual, PropertyModifiers.New, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.NewVirtual, PropertyModifiers.Override, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.NewVirtual, PropertyModifiers.Sealed, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.NewVirtual, PropertyModifiers.Static, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.NewVirtual, PropertyModifiers.Virtual, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.NewVirtual, PropertyModifiers.AbstractOverride, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.NewVirtual, PropertyModifiers.NewAbstract, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.NewVirtual, PropertyModifiers.NewAbstractVirtual, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.NewVirtual, PropertyModifiers.NewStatic, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.NewVirtual, PropertyModifiers.NewVirtual, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.NewVirtual, PropertyModifiers.SealedOverride, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.SealedOverride, PropertyModifiers.None, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.SealedOverride, PropertyModifiers.Abstract, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.SealedOverride, PropertyModifiers.New, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.SealedOverride, PropertyModifiers.Override, SemVerChangeType.Feature)]
        [InlineData(PropertyModifiers.SealedOverride, PropertyModifiers.Sealed, SemVerChangeType.None)]
        [InlineData(PropertyModifiers.SealedOverride, PropertyModifiers.Static, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.SealedOverride, PropertyModifiers.Virtual, SemVerChangeType.Feature)]
        [InlineData(PropertyModifiers.SealedOverride, PropertyModifiers.AbstractOverride, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.SealedOverride, PropertyModifiers.NewAbstract, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.SealedOverride, PropertyModifiers.NewAbstractVirtual, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.SealedOverride, PropertyModifiers.NewStatic, SemVerChangeType.Breaking)]
        [InlineData(PropertyModifiers.SealedOverride, PropertyModifiers.NewVirtual, SemVerChangeType.Feature)]
        [InlineData(PropertyModifiers.SealedOverride, PropertyModifiers.SealedOverride, SemVerChangeType.None)]
        // @formatter:on — enable formatter after this line
        public void CalculateChangeReturnsExpectedValue(
            PropertyModifiers oldModifiers,
            PropertyModifiers newModifiers,
            SemVerChangeType expected)
        {
            var sut = new PropertyModifiersChangeTable();

            var actual = sut.CalculateChange(oldModifiers, newModifiers);

            actual.Should().Be(expected);
        }
    }
}