namespace Neovolve.CodeAnalysis.ChangeTracking.UnitTests
{
    using System.Collections;
    using System.Collections.Generic;

    public class MethodModifierDataSet : IEnumerable<object[]>
    {
        public IEnumerator<object[]> GetEnumerator()
        {
            // NOTE: These values are used in tests where the context is a public method on a public class
            // @formatter:off — disable formatter after this line
            yield return new object[] { "", "", SemVerChangeType.None };
            yield return new object[] {"", "abstract", SemVerChangeType.Breaking};
            yield return new object[] {"", "new", SemVerChangeType.None};
            yield return new object[] {"", "override", SemVerChangeType.Feature};
            yield return new object[] {"", "sealed", SemVerChangeType.None};
            yield return new object[] {"", "static", SemVerChangeType.Breaking};
            yield return new object[] {"", "virtual", SemVerChangeType.Feature};
            yield return new object[] {"", "async", SemVerChangeType.Breaking};
            yield return new object[] {"", "async abstract", SemVerChangeType.Breaking};
            yield return new object[] {"", "async new", SemVerChangeType.Breaking};
            yield return new object[] {"", "async override", SemVerChangeType.Breaking};
            yield return new object[] {"", "async sealed", SemVerChangeType.Breaking};
            yield return new object[] {"", "async static", SemVerChangeType.Breaking};
            yield return new object[] {"", "async virtual", SemVerChangeType.Breaking};
            yield return new object[] {"", "abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"", "new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"", "new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"", "new static", SemVerChangeType.Breaking};
            yield return new object[] {"", "new virtual", SemVerChangeType.Feature};
            yield return new object[] {"", "sealed override", SemVerChangeType.None};
            yield return new object[] {"", "async abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"", "async new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"", "async new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"", "async new static", SemVerChangeType.Breaking};
            yield return new object[] {"", "async new virtual", SemVerChangeType.Breaking};
            yield return new object[] {"", "async sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"abstract", "", SemVerChangeType.Breaking};
            yield return new object[] {"abstract", "new", SemVerChangeType.Breaking};
            yield return new object[] {"abstract", "override", SemVerChangeType.Feature};
            yield return new object[] {"abstract", "sealed", SemVerChangeType.Breaking};
            yield return new object[] {"abstract", "static", SemVerChangeType.Breaking};
            yield return new object[] {"abstract", "virtual", SemVerChangeType.Feature};
            yield return new object[] {"abstract", "async", SemVerChangeType.Breaking};
            yield return new object[] {"abstract", "async abstract", SemVerChangeType.Breaking};
            yield return new object[] {"abstract", "async new", SemVerChangeType.Breaking};
            yield return new object[] {"abstract", "async override", SemVerChangeType.Breaking};
            yield return new object[] {"abstract", "async sealed", SemVerChangeType.Breaking};
            yield return new object[] {"abstract", "async static", SemVerChangeType.Breaking};
            yield return new object[] {"abstract", "async virtual", SemVerChangeType.Breaking};
            yield return new object[] {"abstract", "abstract override", SemVerChangeType.None};
            yield return new object[] {"abstract", "new abstract", SemVerChangeType.None};
            yield return new object[] {"abstract", "new abstract virtual", SemVerChangeType.None};
            yield return new object[] {"abstract", "new static", SemVerChangeType.Breaking};
            yield return new object[] {"abstract", "new virtual", SemVerChangeType.Feature};
            yield return new object[] {"abstract", "sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"abstract", "async abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"abstract", "async new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"abstract", "async new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"abstract", "async new static", SemVerChangeType.Breaking};
            yield return new object[] {"abstract", "async new virtual", SemVerChangeType.Breaking};
            yield return new object[] {"abstract", "async sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"new", "", SemVerChangeType.None};
            yield return new object[] {"new", "abstract", SemVerChangeType.Breaking};
            yield return new object[] {"new", "override", SemVerChangeType.Feature};
            yield return new object[] {"new", "sealed", SemVerChangeType.None};
            yield return new object[] {"new", "static", SemVerChangeType.Breaking};
            yield return new object[] {"new", "virtual", SemVerChangeType.Feature};
            yield return new object[] {"new", "async", SemVerChangeType.Breaking};
            yield return new object[] {"new", "async abstract", SemVerChangeType.Breaking};
            yield return new object[] {"new", "async new", SemVerChangeType.Breaking};
            yield return new object[] {"new", "async override", SemVerChangeType.Breaking};
            yield return new object[] {"new", "async sealed", SemVerChangeType.Breaking};
            yield return new object[] {"new", "async static", SemVerChangeType.Breaking};
            yield return new object[] {"new", "async virtual", SemVerChangeType.Breaking};
            yield return new object[] {"new", "abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"new", "new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"new", "new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"new", "new static", SemVerChangeType.Breaking};
            yield return new object[] {"new", "new virtual", SemVerChangeType.Feature};
            yield return new object[] {"new", "sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"new", "async abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"new", "async new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"new", "async new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"new", "async new static", SemVerChangeType.Breaking};
            yield return new object[] {"new", "async new virtual", SemVerChangeType.Breaking};
            yield return new object[] {"new", "async sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"override", "", SemVerChangeType.Breaking};
            yield return new object[] {"override", "abstract", SemVerChangeType.Breaking};
            yield return new object[] {"override", "new", SemVerChangeType.Breaking};
            yield return new object[] {"override", "sealed", SemVerChangeType.Breaking};
            yield return new object[] {"override", "static", SemVerChangeType.Breaking};
            yield return new object[] {"override", "virtual", SemVerChangeType.None};
            yield return new object[] {"override", "async", SemVerChangeType.Breaking};
            yield return new object[] {"override", "async abstract", SemVerChangeType.Breaking};
            yield return new object[] {"override", "async new", SemVerChangeType.Breaking};
            yield return new object[] {"override", "async override", SemVerChangeType.Breaking};
            yield return new object[] {"override", "async sealed", SemVerChangeType.Breaking};
            yield return new object[] {"override", "async static", SemVerChangeType.Breaking};
            yield return new object[] {"override", "async virtual", SemVerChangeType.Breaking};
            yield return new object[] {"override", "abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"override", "new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"override", "new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"override", "new static", SemVerChangeType.Breaking};
            yield return new object[] {"override", "new virtual", SemVerChangeType.None};
            yield return new object[] {"override", "sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"override", "async abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"override", "async new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"override", "async new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"override", "async new static", SemVerChangeType.Breaking};
            yield return new object[] {"override", "async new virtual", SemVerChangeType.Breaking};
            yield return new object[] {"override", "async sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"sealed", "", SemVerChangeType.None};
            yield return new object[] {"sealed", "abstract", SemVerChangeType.Breaking};
            yield return new object[] {"sealed", "new", SemVerChangeType.None};
            yield return new object[] {"sealed", "override", SemVerChangeType.Feature};
            yield return new object[] {"sealed", "static", SemVerChangeType.Breaking};
            yield return new object[] {"sealed", "virtual", SemVerChangeType.Feature};
            yield return new object[] {"sealed", "async", SemVerChangeType.Breaking};
            yield return new object[] {"sealed", "async abstract", SemVerChangeType.Breaking};
            yield return new object[] {"sealed", "async new", SemVerChangeType.Breaking};
            yield return new object[] {"sealed", "async override", SemVerChangeType.Breaking};
            yield return new object[] {"sealed", "async sealed", SemVerChangeType.Breaking};
            yield return new object[] {"sealed", "async static", SemVerChangeType.Breaking};
            yield return new object[] {"sealed", "async virtual", SemVerChangeType.Breaking};
            yield return new object[] {"sealed", "abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"sealed", "new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"sealed", "new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"sealed", "new static", SemVerChangeType.Breaking};
            yield return new object[] {"sealed", "new virtual", SemVerChangeType.Feature};
            yield return new object[] {"sealed", "sealed override", SemVerChangeType.None};
            yield return new object[] {"sealed", "async abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"sealed", "async new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"sealed", "async new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"sealed", "async new static", SemVerChangeType.Breaking};
            yield return new object[] {"sealed", "async new virtual", SemVerChangeType.Breaking};
            yield return new object[] {"sealed", "async sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"static", "", SemVerChangeType.Breaking};
            yield return new object[] {"static", "abstract", SemVerChangeType.Breaking};
            yield return new object[] {"static", "new", SemVerChangeType.Breaking};
            yield return new object[] {"static", "override", SemVerChangeType.Breaking};
            yield return new object[] {"static", "sealed", SemVerChangeType.Breaking};
            yield return new object[] {"static", "virtual", SemVerChangeType.Breaking};
            yield return new object[] {"static", "async", SemVerChangeType.Breaking};
            yield return new object[] {"static", "async abstract", SemVerChangeType.Breaking};
            yield return new object[] {"static", "async new", SemVerChangeType.Breaking};
            yield return new object[] {"static", "async override", SemVerChangeType.Breaking};
            yield return new object[] {"static", "async sealed", SemVerChangeType.Breaking};
            yield return new object[] {"static", "async static", SemVerChangeType.Breaking};
            yield return new object[] {"static", "async virtual", SemVerChangeType.Breaking};
            yield return new object[] {"static", "abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"static", "new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"static", "new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"static", "new static", SemVerChangeType.None};
            yield return new object[] {"static", "new virtual", SemVerChangeType.Breaking};
            yield return new object[] {"static", "sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"static", "async abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"static", "async new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"static", "async new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"static", "async new static", SemVerChangeType.Breaking};
            yield return new object[] {"static", "async new virtual", SemVerChangeType.Breaking};
            yield return new object[] {"static", "async sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"virtual", "", SemVerChangeType.Breaking};
            yield return new object[] {"virtual", "abstract", SemVerChangeType.Breaking};
            yield return new object[] {"virtual", "new", SemVerChangeType.Breaking};
            yield return new object[] {"virtual", "override", SemVerChangeType.None};
            yield return new object[] {"virtual", "sealed", SemVerChangeType.Breaking};
            yield return new object[] {"virtual", "static", SemVerChangeType.Breaking};
            yield return new object[] {"virtual", "async", SemVerChangeType.Breaking};
            yield return new object[] {"virtual", "async abstract", SemVerChangeType.Breaking};
            yield return new object[] {"virtual", "async new", SemVerChangeType.Breaking};
            yield return new object[] {"virtual", "async override", SemVerChangeType.Breaking};
            yield return new object[] {"virtual", "async sealed", SemVerChangeType.Breaking};
            yield return new object[] {"virtual", "async static", SemVerChangeType.Breaking};
            yield return new object[] {"virtual", "async virtual", SemVerChangeType.Breaking};
            yield return new object[] {"virtual", "abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"virtual", "new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"virtual", "new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"virtual", "new static", SemVerChangeType.Breaking};
            yield return new object[] {"virtual", "new virtual", SemVerChangeType.None};
            yield return new object[] {"virtual", "sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"virtual", "async abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"virtual", "async new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"virtual", "async new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"virtual", "async new static", SemVerChangeType.Breaking};
            yield return new object[] {"virtual", "async new virtual", SemVerChangeType.Breaking};
            yield return new object[] {"virtual", "async sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"async", "", SemVerChangeType.Breaking};
            yield return new object[] {"async", "abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async", "new", SemVerChangeType.Breaking};
            yield return new object[] {"async", "override", SemVerChangeType.Breaking};
            yield return new object[] {"async", "sealed", SemVerChangeType.Breaking};
            yield return new object[] {"async", "static", SemVerChangeType.Breaking};
            yield return new object[] {"async", "virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async", "async abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async", "async new", SemVerChangeType.None};
            yield return new object[] {"async", "async override", SemVerChangeType.Feature};
            yield return new object[] {"async", "async sealed", SemVerChangeType.None};
            yield return new object[] {"async", "async static", SemVerChangeType.Breaking};
            yield return new object[] {"async", "async virtual", SemVerChangeType.Feature};
            yield return new object[] {"async", "abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"async", "new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async", "new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async", "new static", SemVerChangeType.Breaking};
            yield return new object[] {"async", "new virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async", "sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"async", "async abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"async", "async new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async", "async new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async", "async new static", SemVerChangeType.Breaking};
            yield return new object[] {"async", "async new virtual", SemVerChangeType.Feature};
            yield return new object[] {"async", "async sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"async abstract", "", SemVerChangeType.Breaking};
            yield return new object[] {"async abstract", "abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async abstract", "new", SemVerChangeType.Breaking};
            yield return new object[] {"async abstract", "override", SemVerChangeType.Breaking};
            yield return new object[] {"async abstract", "sealed", SemVerChangeType.Breaking};
            yield return new object[] {"async abstract", "static", SemVerChangeType.Breaking};
            yield return new object[] {"async abstract", "virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async abstract", "async", SemVerChangeType.Breaking};
            yield return new object[] {"async abstract", "async new", SemVerChangeType.Breaking};
            yield return new object[] {"async abstract", "async override", SemVerChangeType.Feature};
            yield return new object[] {"async abstract", "async sealed", SemVerChangeType.Breaking};
            yield return new object[] {"async abstract", "async static", SemVerChangeType.Breaking};
            yield return new object[] {"async abstract", "async virtual", SemVerChangeType.Feature};
            yield return new object[] {"async abstract", "abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"async abstract", "new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async abstract", "new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async abstract", "new static", SemVerChangeType.Breaking};
            yield return new object[] {"async abstract", "new virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async abstract", "sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"async abstract", "async abstract override", SemVerChangeType.None};
            yield return new object[] {"async abstract", "async new abstract", SemVerChangeType.None};
            yield return new object[] {"async abstract", "async new abstract virtual", SemVerChangeType.None};
            yield return new object[] {"async abstract", "async new static", SemVerChangeType.Breaking};
            yield return new object[] {"async abstract", "async new virtual", SemVerChangeType.Feature};
            yield return new object[] {"async abstract", "async sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"async new", "", SemVerChangeType.Breaking};
            yield return new object[] {"async new", "abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async new", "new", SemVerChangeType.Breaking};
            yield return new object[] {"async new", "override", SemVerChangeType.Breaking};
            yield return new object[] {"async new", "sealed", SemVerChangeType.Breaking};
            yield return new object[] {"async new", "static", SemVerChangeType.Breaking};
            yield return new object[] {"async new", "virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async new", "async", SemVerChangeType.None};
            yield return new object[] {"async new", "async abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async new", "async override", SemVerChangeType.Feature};
            yield return new object[] {"async new", "async sealed", SemVerChangeType.None};
            yield return new object[] {"async new", "async static", SemVerChangeType.Breaking};
            yield return new object[] {"async new", "async virtual", SemVerChangeType.Feature};
            yield return new object[] {"async new", "abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"async new", "new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async new", "new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async new", "new static", SemVerChangeType.Breaking};
            yield return new object[] {"async new", "new virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async new", "sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"async new", "async abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"async new", "async new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async new", "async new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async new", "async new static", SemVerChangeType.Breaking};
            yield return new object[] {"async new", "async new virtual", SemVerChangeType.Feature};
            yield return new object[] {"async new", "async sealed override", SemVerChangeType.None};
            yield return new object[] {"async override", "", SemVerChangeType.Breaking};
            yield return new object[] {"async override", "abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async override", "new", SemVerChangeType.Breaking};
            yield return new object[] {"async override", "override", SemVerChangeType.Breaking};
            yield return new object[] {"async override", "sealed", SemVerChangeType.Breaking};
            yield return new object[] {"async override", "static", SemVerChangeType.Breaking};
            yield return new object[] {"async override", "virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async override", "async", SemVerChangeType.Breaking};
            yield return new object[] {"async override", "async abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async override", "async new", SemVerChangeType.Breaking};
            yield return new object[] {"async override", "async sealed", SemVerChangeType.Breaking};
            yield return new object[] {"async override", "async static", SemVerChangeType.Breaking};
            yield return new object[] {"async override", "async virtual", SemVerChangeType.Feature};
            yield return new object[] {"async override", "abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"async override", "new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async override", "new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async override", "new static", SemVerChangeType.Breaking};
            yield return new object[] {"async override", "new virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async override", "sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"async override", "async abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"async override", "async new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async override", "async new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async override", "async new static", SemVerChangeType.Breaking};
            yield return new object[] {"async override", "async new virtual", SemVerChangeType.Feature};
            yield return new object[] {"async override", "async sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed", "", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed", "abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed", "new", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed", "override", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed", "sealed", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed", "static", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed", "virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed", "async", SemVerChangeType.None};
            yield return new object[] {"async sealed", "async abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed", "async new", SemVerChangeType.None};
            yield return new object[] {"async sealed", "async override", SemVerChangeType.Feature};
            yield return new object[] {"async sealed", "async static", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed", "async virtual", SemVerChangeType.Feature};
            yield return new object[] {"async sealed", "abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed", "new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed", "new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed", "new static", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed", "new virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed", "sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed", "async abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed", "async new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed", "async new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed", "async new static", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed", "async new virtual", SemVerChangeType.Feature};
            yield return new object[] {"async sealed", "async sealed override", SemVerChangeType.None};
            yield return new object[] {"async static", "", SemVerChangeType.Breaking};
            yield return new object[] {"async static", "abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async static", "new", SemVerChangeType.Breaking};
            yield return new object[] {"async static", "override", SemVerChangeType.Breaking};
            yield return new object[] {"async static", "sealed", SemVerChangeType.Breaking};
            yield return new object[] {"async static", "static", SemVerChangeType.Breaking};
            yield return new object[] {"async static", "virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async static", "async", SemVerChangeType.Breaking};
            yield return new object[] {"async static", "async abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async static", "async new", SemVerChangeType.Breaking};
            yield return new object[] {"async static", "async override", SemVerChangeType.Breaking};
            yield return new object[] {"async static", "async sealed", SemVerChangeType.Breaking};
            yield return new object[] {"async static", "async virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async static", "abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"async static", "new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async static", "new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async static", "new static", SemVerChangeType.Breaking};
            yield return new object[] {"async static", "new virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async static", "sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"async static", "async abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"async static", "async new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async static", "async new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async static", "async new static", SemVerChangeType.None};
            yield return new object[] {"async static", "async new virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async static", "async sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"async virtual", "", SemVerChangeType.Breaking};
            yield return new object[] {"async virtual", "abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async virtual", "new", SemVerChangeType.Breaking};
            yield return new object[] {"async virtual", "override", SemVerChangeType.Breaking};
            yield return new object[] {"async virtual", "sealed", SemVerChangeType.Breaking};
            yield return new object[] {"async virtual", "static", SemVerChangeType.Breaking};
            yield return new object[] {"async virtual", "virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async virtual", "async", SemVerChangeType.Breaking};
            yield return new object[] {"async virtual", "async abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async virtual", "async new", SemVerChangeType.Breaking};
            yield return new object[] {"async virtual", "async override", SemVerChangeType.None};
            yield return new object[] {"async virtual", "async sealed", SemVerChangeType.Breaking};
            yield return new object[] {"async virtual", "async static", SemVerChangeType.Breaking};
            yield return new object[] {"async virtual", "abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"async virtual", "new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async virtual", "new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async virtual", "new static", SemVerChangeType.Breaking};
            yield return new object[] {"async virtual", "new virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async virtual", "sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"async virtual", "async abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"async virtual", "async new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async virtual", "async new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async virtual", "async new static", SemVerChangeType.Breaking};
            yield return new object[] {"async virtual", "async new virtual", SemVerChangeType.None};
            yield return new object[] {"async virtual", "async sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"abstract override", "", SemVerChangeType.Breaking};
            yield return new object[] {"abstract override", "abstract", SemVerChangeType.None};
            yield return new object[] {"abstract override", "new", SemVerChangeType.Breaking};
            yield return new object[] {"abstract override", "override", SemVerChangeType.Feature};
            yield return new object[] {"abstract override", "sealed", SemVerChangeType.Breaking};
            yield return new object[] {"abstract override", "static", SemVerChangeType.Breaking};
            yield return new object[] {"abstract override", "virtual", SemVerChangeType.Feature};
            yield return new object[] {"abstract override", "async", SemVerChangeType.Breaking};
            yield return new object[] {"abstract override", "async abstract", SemVerChangeType.Breaking};
            yield return new object[] {"abstract override", "async new", SemVerChangeType.Breaking};
            yield return new object[] {"abstract override", "async override", SemVerChangeType.Breaking};
            yield return new object[] {"abstract override", "async sealed", SemVerChangeType.Breaking};
            yield return new object[] {"abstract override", "async static", SemVerChangeType.Breaking};
            yield return new object[] {"abstract override", "async virtual", SemVerChangeType.Breaking};
            yield return new object[] {"abstract override", "new abstract", SemVerChangeType.None};
            yield return new object[] {"abstract override", "new abstract virtual", SemVerChangeType.None};
            yield return new object[] {"abstract override", "new static", SemVerChangeType.Breaking};
            yield return new object[] {"abstract override", "new virtual", SemVerChangeType.Feature};
            yield return new object[] {"abstract override", "sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"abstract override", "async abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"abstract override", "async new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"abstract override", "async new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"abstract override", "async new static", SemVerChangeType.Breaking};
            yield return new object[] {"abstract override", "async new virtual", SemVerChangeType.Breaking};
            yield return new object[] {"abstract override", "async sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"new abstract", "", SemVerChangeType.Breaking};
            yield return new object[] {"new abstract", "abstract", SemVerChangeType.None};
            yield return new object[] {"new abstract", "new", SemVerChangeType.Breaking};
            yield return new object[] {"new abstract", "override", SemVerChangeType.Feature};
            yield return new object[] {"new abstract", "sealed", SemVerChangeType.Breaking};
            yield return new object[] {"new abstract", "static", SemVerChangeType.Breaking};
            yield return new object[] {"new abstract", "virtual", SemVerChangeType.Feature};
            yield return new object[] {"new abstract", "async", SemVerChangeType.Breaking};
            yield return new object[] {"new abstract", "async abstract", SemVerChangeType.Breaking};
            yield return new object[] {"new abstract", "async new", SemVerChangeType.Breaking};
            yield return new object[] {"new abstract", "async override", SemVerChangeType.Breaking};
            yield return new object[] {"new abstract", "async sealed", SemVerChangeType.Breaking};
            yield return new object[] {"new abstract", "async static", SemVerChangeType.Breaking};
            yield return new object[] {"new abstract", "async virtual", SemVerChangeType.Breaking};
            yield return new object[] {"new abstract", "abstract override", SemVerChangeType.None};
            yield return new object[] {"new abstract", "new abstract virtual", SemVerChangeType.None};
            yield return new object[] {"new abstract", "new static", SemVerChangeType.Breaking};
            yield return new object[] {"new abstract", "new virtual", SemVerChangeType.Feature};
            yield return new object[] {"new abstract", "sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"new abstract", "async abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"new abstract", "async new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"new abstract", "async new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"new abstract", "async new static", SemVerChangeType.Breaking};
            yield return new object[] {"new abstract", "async new virtual", SemVerChangeType.Breaking};
            yield return new object[] {"new abstract", "async sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"new abstract virtual", "", SemVerChangeType.Breaking};
            yield return new object[] {"new abstract virtual", "abstract", SemVerChangeType.None};
            yield return new object[] {"new abstract virtual", "new", SemVerChangeType.Breaking};
            yield return new object[] {"new abstract virtual", "override", SemVerChangeType.Feature};
            yield return new object[] {"new abstract virtual", "sealed", SemVerChangeType.Breaking};
            yield return new object[] {"new abstract virtual", "static", SemVerChangeType.Breaking};
            yield return new object[] {"new abstract virtual", "virtual", SemVerChangeType.Feature};
            yield return new object[] {"new abstract virtual", "async", SemVerChangeType.Breaking};
            yield return new object[] {"new abstract virtual", "async abstract", SemVerChangeType.Breaking};
            yield return new object[] {"new abstract virtual", "async new", SemVerChangeType.Breaking};
            yield return new object[] {"new abstract virtual", "async override", SemVerChangeType.Breaking};
            yield return new object[] {"new abstract virtual", "async sealed", SemVerChangeType.Breaking};
            yield return new object[] {"new abstract virtual", "async static", SemVerChangeType.Breaking};
            yield return new object[] {"new abstract virtual", "async virtual", SemVerChangeType.Breaking};
            yield return new object[] {"new abstract virtual", "abstract override", SemVerChangeType.None};
            yield return new object[] {"new abstract virtual", "new abstract", SemVerChangeType.None};
            yield return new object[] {"new abstract virtual", "new static", SemVerChangeType.Breaking};
            yield return new object[] {"new abstract virtual", "new virtual", SemVerChangeType.Feature};
            yield return new object[] {"new abstract virtual", "sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"new abstract virtual", "async abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"new abstract virtual", "async new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"new abstract virtual", "async new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"new abstract virtual", "async new static", SemVerChangeType.Breaking};
            yield return new object[] {"new abstract virtual", "async new virtual", SemVerChangeType.Breaking};
            yield return new object[] {"new abstract virtual", "async sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"new static", "", SemVerChangeType.Breaking};
            yield return new object[] {"new static", "abstract", SemVerChangeType.Breaking};
            yield return new object[] {"new static", "new", SemVerChangeType.Breaking};
            yield return new object[] {"new static", "override", SemVerChangeType.Breaking};
            yield return new object[] {"new static", "sealed", SemVerChangeType.Breaking};
            yield return new object[] {"new static", "static", SemVerChangeType.None};
            yield return new object[] {"new static", "virtual", SemVerChangeType.Breaking};
            yield return new object[] {"new static", "async", SemVerChangeType.Breaking};
            yield return new object[] {"new static", "async abstract", SemVerChangeType.Breaking};
            yield return new object[] {"new static", "async new", SemVerChangeType.Breaking};
            yield return new object[] {"new static", "async override", SemVerChangeType.Breaking};
            yield return new object[] {"new static", "async sealed", SemVerChangeType.Breaking};
            yield return new object[] {"new static", "async static", SemVerChangeType.Breaking};
            yield return new object[] {"new static", "async virtual", SemVerChangeType.Breaking};
            yield return new object[] {"new static", "abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"new static", "new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"new static", "new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"new static", "new virtual", SemVerChangeType.Breaking};
            yield return new object[] {"new static", "sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"new static", "async abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"new static", "async new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"new static", "async new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"new static", "async new static", SemVerChangeType.Breaking};
            yield return new object[] {"new static", "async new virtual", SemVerChangeType.Breaking};
            yield return new object[] {"new static", "async sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"new virtual", "", SemVerChangeType.Breaking};
            yield return new object[] {"new virtual", "abstract", SemVerChangeType.Breaking};
            yield return new object[] {"new virtual", "new", SemVerChangeType.Breaking};
            yield return new object[] {"new virtual", "override", SemVerChangeType.None};
            yield return new object[] {"new virtual", "sealed", SemVerChangeType.Breaking};
            yield return new object[] {"new virtual", "static", SemVerChangeType.Breaking};
            yield return new object[] {"new virtual", "virtual", SemVerChangeType.None};
            yield return new object[] {"new virtual", "async", SemVerChangeType.Breaking};
            yield return new object[] {"new virtual", "async abstract", SemVerChangeType.Breaking};
            yield return new object[] {"new virtual", "async new", SemVerChangeType.Breaking};
            yield return new object[] {"new virtual", "async override", SemVerChangeType.Breaking};
            yield return new object[] {"new virtual", "async sealed", SemVerChangeType.Breaking};
            yield return new object[] {"new virtual", "async static", SemVerChangeType.Breaking};
            yield return new object[] {"new virtual", "async virtual", SemVerChangeType.Breaking};
            yield return new object[] {"new virtual", "abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"new virtual", "new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"new virtual", "new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"new virtual", "new static", SemVerChangeType.Breaking};
            yield return new object[] {"new virtual", "sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"new virtual", "async abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"new virtual", "async new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"new virtual", "async new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"new virtual", "async new static", SemVerChangeType.Breaking};
            yield return new object[] {"new virtual", "async new virtual", SemVerChangeType.Breaking};
            yield return new object[] {"new virtual", "async sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"sealed override", "", SemVerChangeType.None};
            yield return new object[] {"sealed override", "abstract", SemVerChangeType.Breaking};
            yield return new object[] {"sealed override", "new", SemVerChangeType.None};
            yield return new object[] {"sealed override", "override", SemVerChangeType.Feature};
            yield return new object[] {"sealed override", "sealed", SemVerChangeType.None};
            yield return new object[] {"sealed override", "static", SemVerChangeType.Breaking};
            yield return new object[] {"sealed override", "virtual", SemVerChangeType.Feature};
            yield return new object[] {"sealed override", "async", SemVerChangeType.Breaking};
            yield return new object[] {"sealed override", "async abstract", SemVerChangeType.Breaking};
            yield return new object[] {"sealed override", "async new", SemVerChangeType.Breaking};
            yield return new object[] {"sealed override", "async override", SemVerChangeType.Breaking};
            yield return new object[] {"sealed override", "async sealed", SemVerChangeType.Breaking};
            yield return new object[] {"sealed override", "async static", SemVerChangeType.Breaking};
            yield return new object[] {"sealed override", "async virtual", SemVerChangeType.Breaking};
            yield return new object[] {"sealed override", "abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"sealed override", "new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"sealed override", "new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"sealed override", "new static", SemVerChangeType.Breaking};
            yield return new object[] {"sealed override", "new virtual", SemVerChangeType.Feature};
            yield return new object[] {"sealed override", "async abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"sealed override", "async new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"sealed override", "async new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"sealed override", "async new static", SemVerChangeType.Breaking};
            yield return new object[] {"sealed override", "async new virtual", SemVerChangeType.Breaking};
            yield return new object[] {"sealed override", "async sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"async abstract override", "", SemVerChangeType.Breaking};
            yield return new object[] {"async abstract override", "abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async abstract override", "new", SemVerChangeType.Breaking};
            yield return new object[] {"async abstract override", "override", SemVerChangeType.Breaking};
            yield return new object[] {"async abstract override", "sealed", SemVerChangeType.Breaking};
            yield return new object[] {"async abstract override", "static", SemVerChangeType.Breaking};
            yield return new object[] {"async abstract override", "virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async abstract override", "async", SemVerChangeType.Breaking};
            yield return new object[] {"async abstract override", "async abstract", SemVerChangeType.None};
            yield return new object[] {"async abstract override", "async new", SemVerChangeType.Breaking};
            yield return new object[] {"async abstract override", "async override", SemVerChangeType.Feature};
            yield return new object[] {"async abstract override", "async sealed", SemVerChangeType.Breaking};
            yield return new object[] {"async abstract override", "async static", SemVerChangeType.Breaking};
            yield return new object[] {"async abstract override", "async virtual", SemVerChangeType.Feature};
            yield return new object[] {"async abstract override", "abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"async abstract override", "new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async abstract override", "new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async abstract override", "new static", SemVerChangeType.Breaking};
            yield return new object[] {"async abstract override", "new virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async abstract override", "sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"async abstract override", "async new abstract", SemVerChangeType.None};
            yield return new object[] {"async abstract override", "async new abstract virtual", SemVerChangeType.None};
            yield return new object[] {"async abstract override", "async new static", SemVerChangeType.Breaking};
            yield return new object[] {"async abstract override", "async new virtual", SemVerChangeType.Feature};
            yield return new object[] {"async abstract override", "async sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"async new abstract", "", SemVerChangeType.Breaking};
            yield return new object[] {"async new abstract", "abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async new abstract", "new", SemVerChangeType.Breaking};
            yield return new object[] {"async new abstract", "override", SemVerChangeType.Breaking};
            yield return new object[] {"async new abstract", "sealed", SemVerChangeType.Breaking};
            yield return new object[] {"async new abstract", "static", SemVerChangeType.Breaking};
            yield return new object[] {"async new abstract", "virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async new abstract", "async", SemVerChangeType.Breaking};
            yield return new object[] {"async new abstract", "async abstract", SemVerChangeType.None};
            yield return new object[] {"async new abstract", "async new", SemVerChangeType.Breaking};
            yield return new object[] {"async new abstract", "async override", SemVerChangeType.Feature};
            yield return new object[] {"async new abstract", "async sealed", SemVerChangeType.Breaking};
            yield return new object[] {"async new abstract", "async static", SemVerChangeType.Breaking};
            yield return new object[] {"async new abstract", "async virtual", SemVerChangeType.Feature};
            yield return new object[] {"async new abstract", "abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"async new abstract", "new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async new abstract", "new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async new abstract", "new static", SemVerChangeType.Breaking};
            yield return new object[] {"async new abstract", "new virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async new abstract", "sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"async new abstract", "async abstract override", SemVerChangeType.None};
            yield return new object[] {"async new abstract", "async new abstract virtual", SemVerChangeType.None};
            yield return new object[] {"async new abstract", "async new static", SemVerChangeType.Breaking};
            yield return new object[] {"async new abstract", "async new virtual", SemVerChangeType.Feature};
            yield return new object[] {"async new abstract", "async sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"async new abstract virtual", "", SemVerChangeType.Breaking};
            yield return new object[] {"async new abstract virtual", "abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async new abstract virtual", "new", SemVerChangeType.Breaking};
            yield return new object[] {"async new abstract virtual", "override", SemVerChangeType.Breaking};
            yield return new object[] {"async new abstract virtual", "sealed", SemVerChangeType.Breaking};
            yield return new object[] {"async new abstract virtual", "static", SemVerChangeType.Breaking};
            yield return new object[] {"async new abstract virtual", "virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async new abstract virtual", "async", SemVerChangeType.Breaking};
            yield return new object[] {"async new abstract virtual", "async abstract", SemVerChangeType.None};
            yield return new object[] {"async new abstract virtual", "async new", SemVerChangeType.Breaking};
            yield return new object[] {"async new abstract virtual", "async override", SemVerChangeType.Feature};
            yield return new object[] {"async new abstract virtual", "async sealed", SemVerChangeType.Breaking};
            yield return new object[] {"async new abstract virtual", "async static", SemVerChangeType.Breaking};
            yield return new object[] {"async new abstract virtual", "async virtual", SemVerChangeType.Feature};
            yield return new object[] {"async new abstract virtual", "abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"async new abstract virtual", "new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async new abstract virtual", "new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async new abstract virtual", "new static", SemVerChangeType.Breaking};
            yield return new object[] {"async new abstract virtual", "new virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async new abstract virtual", "sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"async new abstract virtual", "async abstract override", SemVerChangeType.None};
            yield return new object[] {"async new abstract virtual", "async new abstract", SemVerChangeType.None};
            yield return new object[] {"async new abstract virtual", "async new static", SemVerChangeType.Breaking};
            yield return new object[] {"async new abstract virtual", "async new virtual", SemVerChangeType.Feature};
            yield return new object[] {"async new abstract virtual", "async sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"async new static", "", SemVerChangeType.Breaking};
            yield return new object[] {"async new static", "abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async new static", "new", SemVerChangeType.Breaking};
            yield return new object[] {"async new static", "override", SemVerChangeType.Breaking};
            yield return new object[] {"async new static", "sealed", SemVerChangeType.Breaking};
            yield return new object[] {"async new static", "static", SemVerChangeType.Breaking};
            yield return new object[] {"async new static", "virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async new static", "async", SemVerChangeType.Breaking};
            yield return new object[] {"async new static", "async abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async new static", "async new", SemVerChangeType.Breaking};
            yield return new object[] {"async new static", "async override", SemVerChangeType.Breaking};
            yield return new object[] {"async new static", "async sealed", SemVerChangeType.Breaking};
            yield return new object[] {"async new static", "async static", SemVerChangeType.None};
            yield return new object[] {"async new static", "async virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async new static", "abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"async new static", "new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async new static", "new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async new static", "new static", SemVerChangeType.Breaking};
            yield return new object[] {"async new static", "new virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async new static", "sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"async new static", "async abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"async new static", "async new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async new static", "async new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async new static", "async new virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async new static", "async sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"async new virtual", "", SemVerChangeType.Breaking};
            yield return new object[] {"async new virtual", "abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async new virtual", "new", SemVerChangeType.Breaking};
            yield return new object[] {"async new virtual", "override", SemVerChangeType.Breaking};
            yield return new object[] {"async new virtual", "sealed", SemVerChangeType.Breaking};
            yield return new object[] {"async new virtual", "static", SemVerChangeType.Breaking};
            yield return new object[] {"async new virtual", "virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async new virtual", "async", SemVerChangeType.Breaking};
            yield return new object[] {"async new virtual", "async abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async new virtual", "async new", SemVerChangeType.Breaking};
            yield return new object[] {"async new virtual", "async override", SemVerChangeType.None};
            yield return new object[] {"async new virtual", "async sealed", SemVerChangeType.Breaking};
            yield return new object[] {"async new virtual", "async static", SemVerChangeType.Breaking};
            yield return new object[] {"async new virtual", "async virtual", SemVerChangeType.None};
            yield return new object[] {"async new virtual", "abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"async new virtual", "new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async new virtual", "new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async new virtual", "new static", SemVerChangeType.Breaking};
            yield return new object[] {"async new virtual", "new virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async new virtual", "sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"async new virtual", "async abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"async new virtual", "async new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async new virtual", "async new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async new virtual", "async new static", SemVerChangeType.Breaking};
            yield return new object[] {"async new virtual", "async sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed override", "", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed override", "abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed override", "new", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed override", "override", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed override", "sealed", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed override", "static", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed override", "virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed override", "async", SemVerChangeType.None};
            yield return new object[] {"async sealed override", "async abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed override", "async new", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed override", "async override", SemVerChangeType.Feature};
            yield return new object[] {"async sealed override", "async sealed", SemVerChangeType.None};
            yield return new object[] {"async sealed override", "async static", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed override", "async virtual", SemVerChangeType.Feature};
            yield return new object[] {"async sealed override", "abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed override", "new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed override", "new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed override", "new static", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed override", "new virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed override", "sealed override", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed override", "async abstract override", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed override", "async new abstract", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed override", "async new abstract virtual", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed override", "async new static", SemVerChangeType.Breaking};
            yield return new object[] {"async sealed override", "async new virtual", SemVerChangeType.Feature};
            // @formatter:on — enable formatter after this line
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }
    }
}