name: CI

on: 
  push
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Fetch tags and master for GitVersion
      run: |
        git fetch --tags
        git branch --create-reflog master origin/master

    - name: GitVersion
      uses: docker://gittools/gitversion:5.0.2-linux
      with:
        args: /github/workspace /nofetch /exec /bin/sh /execargs "-c \"echo $GitVersion_NuGetVersionV2\\r\\n$GitVersion_AssemblySemVer\\r\\n$GitVersion_MajorMinorPatch\\r\\n$GitVersion_InformationalVersion > /github/workspace/version.txt\""
    
    - name: Version projects
      uses: docker://mcr.microsoft.com/powershell:alpine-3.8
      with:
        args: pwsh /github/workspace/version-projects.ps1
    
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100' # SDK Version to use.

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Test
      run: dotnet test -c Release --no-build /p:CollectCoverage=true /p:CoverletOutput="$GITHUB_WORKSPACE/coverage/lcov.info" /p:MergeWith="$GITHUB_WORKSPACE/coverage/lcov.info" /p:CoverletOutputFormat=lcov                                                       
    
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: /home/runner/work/Neovolve.CodeAnalysis.ChangeTracking/Neovolve.CodeAnalysis.ChangeTracking/coverage/lcov.info
    
    - name: Pack
      run: dotnet pack "./Neovolve.CodeAnalysis.ChangeTracking/Neovolve.CodeAnalysis.ChangeTracking.csproj" -c Release --no-build --include-symbols -o ./staging

    - name: Setup nuget
      uses: olegtarasov/download-nuget@v1

    - name: Publish to MyGet.org
      run: nuget push ./staging/Neovolve.CodeAnalysis.ChangeTracking.$GitVersion_NuGetVersionV2.symbols.nupkg $MYGET_APIKEY -source https://www.myget.org/F/neovolve/api/v2/package
      if: github.event_name == 'pull_request'

    - name: Publish to NuGet.org
      run: nuget push ./staging/Neovolve.CodeAnalysis.ChangeTracking.$GitVersion_NuGetVersionV2.symbols.nupkg $NUGET_APIKEY -source https://api.nuget.org/v3/index.json
      if: github.ref == 'master' 
