name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COVERAGE_PATH: $GITHUB_WORKSPACE/coverage/lcov.info
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Fetch tags and master for GitVersion
      run: |
        git fetch --tags
        git branch --create-reflog master origin/master

    - name: GitVersion
      uses: docker://gittools/gitversion:5.0.2-linux
      with:
        args: /github/workspace /nofetch /exec /bin/sh /execargs "-c \"echo $GitVersion_NuGetVersionV2\\r\\n$GitVersion_AssemblySemVer\\r\\n$GitVersion_MajorMinorPatch\\r\\n$GitVersion_InformationalVersion > /github/workspace/version.txt\""
    
    - name: Version projects
      uses: docker://mcr.microsoft.com/powershell:alpine-3.8
      with:
        args: pwsh /github/workspace/version-projects.ps1
    
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100' # SDK Version to use.

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Test
      run: dotnet test -c Release --no-build /p:CollectCoverage=true /p:CoverletOutput="$COVERAGE_PATH" /p:MergeWith="$COVERAGE_PATH" /p:CoverletOutputFormat=lcov                                                       
      
    - name: List directory
      run: |
        ls $GITHUB_WORKSPACE
        ls $GITHUB_WORKSPACE/coverage
        
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: "$COVERAGE_PATH"
    
    - name: Pack
      run: dotnet pack "./Neovolve.CodeAnalysis.ChangeTracking/Neovolve.CodeAnalysis.ChangeTracking.csproj" -c Release --no-build --include-symbols -o ./staging
